language: node_js

node_js:
  - 6.6.0

sudo: true

dist: trusty

addons:
  firefox: latest
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable

branches:
  only:
    - master

cache:
  yarn: true
  directories:
  - node_modules

script:
  - npm --version
  - yarn --version
  - npm install -g bower
  - bower install
  - npm run lint
  - xvfb-run wct
  - npm run build
